#!/bin/bash

filename="simplewiki.xml"
tmpname1="tmp1"
tmpname2="tmp2"
finalfilename="simplewiki.txt"

echo "Removing Newline..."
cat "$filename" | tr '\n' ' '  > "$tmpname1"
echo "Removing * ..."
sed -e 's/\*//g' "$tmpname1" > "$tmpname2"
mv "$tmpname2" "$tmpname1"
echo "Replace <page> with newlines..."
sed -e $'s/<page>/\\\n/g' "$tmpname1" > "$tmpname2"
mv "$tmpname2" "$tmpname1"
echo "Removing First Line..."
tail -n +2 "$tmpname1" > "$tmpname2"
mv "$tmpname2" "$tmpname1"
echo "Removing All Tags..."
sed -e 's/<[^>]*>//g' "$tmpname1" > "$tmpname2"
mv "$tmpname2" "$tmpname1"
echo "Removing all special characters except alphanumeric characters..."
sed -e 's/[^a-zA-Z*0-9]/ /g' "$tmpname1" > "$tmpname2"
mv "$tmpname2" "$tmpname1"
echo "Replace multiple space with a single space..."
sed -e 's/  */ /g' "$tmpname1" > "$tmpname2"
mv "$tmpname2" "$finalfilename"
rm -rf "$tmpname1"

